# appspec.yml
version: 0.0
os: linux
files:
  - source: / # CodeDeploy zip 파일의 모든 내용을
    destination: /home/ec2-user/app/ # EC2 인스턴스의 이 폴더로 복사합니다.
    overwrite: yes

permissions:
  - object: /home/ec2-user/app
    pattern: "**"
    owner: ec2-user
    group: ec2-user

  - object: /home/ec2-user/app/scripts/deploy.sh
    owner: ec2-user
    group: ec2-user
    mode: 755

hooks:
  ApplicationStart: # 배포의 'ApplicationStart' 단계에서
    - location: scripts/deploy.sh # 이 스크립트를 실행합니다.
      timeout: 180 # 180초 안에 끝나야 합니다.
      runas: ec2-user # ec2-user 권한으로 실행합니다.
