spring:
  application:
    name: my-pocket
#  cloud:
#    aws:
#      region:
#        static: ap-northeast-2
#  config:
#    import: ""
  config:
    import: aws-parameterstore:/config/my-pocket/
  datasource:
    url: jdbc:mysql://${db.host}:3306/${db.name}?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: ${db.username}
    password: ${db.password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: ture
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.MySQL8Dialect
  cache:
    type: redis
  data:
    redis:
      timeout: 6000
      host: ${redis.host}
      port: 6379
  mvc:
    log-request-details: true

kakao:
  restapi:
    key: ${api.kakao}
  api:
    baseurl: https://dapi.kakao.com
    path:
      book: /v3/search/book

#logging:
#  level:
#    org.springframework.web: DEBUG
#    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
#  pattern:
#    console: "%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n"