spring:
  config:
    import: aws-parameterstore:/config/
  application:
    name: my-pocket
  datasource:
    url: jdbc:mysql://${db.host}:3306/${db.name}?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: ${db.username}
    password: ${db.password}
  mvc:
    log-request-details: true

kakao:
  restapi:
    key: ${api.kakao}
  api:
    baseurl: https://dapi.kakao.com
    path:
      book: /v3/search/book

logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n"